Karls copy changes
rfussell17/tpc-site pull request #1
Opened 2023-08-09 11:28 UTC by karllhughes

@manualwise @rfussell17 I made a bunch of copy changes to the homepage here. More coming as I have time!

2023-08-09 11:29 UTC, karllhughes commented on components/book-discovery-call.tsx
> +                  Book a Call <span aria-hidden="true">&rarr;</span>
Small consistency thing, but let's use the wording "Book a Call" everywhere.

This should also link to a page on our site that we can embed Calendly on rather than the Calendly directly. That way, we can swap out the calendly link later when we have multiple sales people.

2023-08-09 11:31 UTC, karllhughes commented on components/feature.tsx
>    },
@manualwise I decided to switch the order of these up. The first feature block shows our most common services as this is what most people booking a call need.

Then, the other block talks about secondary services.

2023-08-10 14:13 UTC, manualwise commented on components/feature.tsx
>    },
Good with me!

2023-08-10 14:20 UTC, manualwise requested changes

2023-08-10 14:20 UTC, manualwise commented on components/feature.tsx
> +      "See how your show compares to the top shows in the industry. During our podcast audit, we'll make sure your show is positioned properly based on your audience, that the audio and production qu
~we'll make sure~ --> our experienced team makes sure

(this is to extend the last line a bit so we, visually, don't just have a *single* word in it.

2023-08-10 14:20 UTC, manualwise commented on components/small-stats.tsx
> +              A Proven Track Record of Success
I'd rather not implement your change here as this H2 is created like this for SEO purposes.

2023-08-10 14:20 UTC, manualwise commented on components/secondary-services.tsx
> +      "Engage your users and have regular content for YouTube by adding video to your podcast. We can help you plan and launch a video podcast or take the ongoing production work off your plate.",
would add a mention of Vimeo here, just because it's the 2nd most used platform and it would help us extend the feature block by a few words to make it visually look better

2023-08-10 14:20 UTC, manualwise commented on components/secondary-services.tsx
> +      "Record with confidence knowing all the technical aspects are covered. Our remote recording specialists are experienced audio engineers who can ensure a high-quality recording so you and your g
to remove a few words and make the feature block as long as the others I'd change this to:

Our remote recording specialists are experienced engineers who ensure a high-quality recording so you and your guests can focus on the content.

2023-08-10 14:20 UTC, manualwise commented on components/secondary-services.tsx
> +    description: "Ensure your show gets as much reach as possible. Our team can produce audio and video clips, audiograms, and social media images for each episode.",
Ensure you have enough assets that help you promote your show so it gets as much reach as possible

(again, this is done in order for all feature blocks to have the same line number)

2023-08-10 14:20 UTC, manualwise commented on components/feature.tsx
FYI: you added the ClipboardDocumentCheckIcon here without adding it at the top of the features.tsx file - when you go over this suggested changes, please remove the `VideoCameraIcon` import at the top of the page and replace it with the `ClipboardDocumentCheckIcon` that's used for the audit feature block

2023-08-11 13:59 UTC, manualwise commented on components/feature.tsx
> +            From launching a new show to improving an existing one
as per our convo on Slack, this h2 actually would also benefit from having "Podcast Lauch" or similar. Maybe a compromise like "From launching a new podcast to improving an existing one" works?

2023-08-18 14:25 UTC, merged